---
title: "deepSentimentR"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{deepSentimentR}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE, 
  warning = FALSE,
  error = FALSE
)
```

```{r setup}
library(dplyr)
library(deepSentimentR)

data("sentiment140_train")

sentiment140_train %>% 
  freq_by_polarity(user_list = c("", "mcraddictal"), 
                   start_date_time = lubridate::as_datetime("2009-05-30"),
                   end_date_time = lubridate::as_datetime("2009-06-03"),
                   keyword_list = c(""))
```

```{r time_series}
time_series()
```

```{r bigram_network}
bigram_network()
```

```{r word_cor_network}
word_cor_network()
```

```{r predict_lstm}
predict_polarity_keras(model_load_path = system.file("extdata",
                                                     "train_no_glove_lstm.rds",
                                                     package = "deepSentimentR",
                                                     mustWork = TRUE))
```


```{r predict_lstm_glove}
predict_polarity_keras(model_load_path = system.file("extdata",
                                                     "train_glove_lstm.rds",
                                                     package = "deepSentimentR",
                                                     mustWork = TRUE))
```

```{r predict_conv1d}
predict_polarity_keras(model_load_path = system.file("extdata",
                                                     "train_no_glove_conv_1d.rds",
                                                     package = "deepSentimentR",
                                                     mustWork = TRUE))
```

```{r predict_conv1d_glove}
predict_polarity_keras(model_load_path = system.file("extdata",
                                                     "train_glove_conv_1d.rds",
                                                     package = "deepSentimentR",
                                                     mustWork = TRUE))
```
